---
title: "Democracy's Data"
subtitle: "An Introduction to Essential Data for Democracy"
author: "Jeremy Mikecz"
institute: "Research Data Services, Dartmouth Libraries"
date: "October 2024"
format: 
  revealjs:
    theme: sky
    navigation-mode: vertical
editor: visual
logo: "images/logo_white.png"
---

## Data & Democracy 

::: incremental
1.  What conditions does a society need for democracy to function effectively?
2.  How can we measure or quantify the presence of these conditions?
:::

::: notes
counter question - What conditions allow the rise of authoritarian leaders & governments?

Timothy Snyder, Hannah Arendt

The Big Lie
:::

# Democracy's Data

What is the role of data in a democracy?

**\[IMAGE: HEADLINES ABOUT DEMOCRACY\]**

::: notes
Why

1.  democracy threatened {democracy headlines}
2.  Jan. 6 headlines
3.  \[Dem side - changing courts??\]
4.  Bouk book
:::

## Democracy's Data Workshop Series

Wed. 10/9: Democracy's Data: An Introduction to Essential Data for Democracy

Wed. 10/23 Democracy's Data 2: Counting People, Examining Census Data in R

Wed. 10/30 Democracy's Data 3: Attitudes about Democracy and Elections - Working with Gallup Data in R

## Series Goals

## Today's Goals
